# mkdocs.yml
# Configuration file for MkDocs

site_name: Pro Analytics 02
site_url: https://denisecase.github.io/pro-analytics-02/
repo_url: https://github.com/denisecase/pro-analytics-02
site_description: Guide to Professional Python projects using industry best practices
site_author: Denise Case
docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - navigation.expand # Expand navigation by default
    - navigation.sections # Group navigation items
    - navigation.top # Back-to-top button
    - navigation.tracking # Track active section
    - navigation.paths # Breadcrumbs
    - search.suggest # Search suggestions as you type
    - search.highlight # Highlight search terms
    - content.code.copy # Copy button on code blocks
    - toc.follow # Highlight current section in TOC

  palette:
    - scheme: default # Light/dark mode toggle
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true # Include module names
            show_root_toc_entry: true # Include module in TOC
            docstring_style: google # Professional docstring format
            show_signature_annotations: true
            separate_signature: true    # Makes function signatures easier to read

markdown_extensions:
  - admonition # Note/Warning/Tip boxes
  - codehilite # Syntax highlighting
  - tables # Markdown tables
  - toc:
      permalink: true # Clickable headers
      toc_depth: 3
  - pymdownx.superfences # Code blocks with syntax highlighting
  - pymdownx.details # Collapsible sections

nav:
  - Home: index.md

  - "1: Set Up Machine":
      - Overview (click here): 01-set-up-machine/index.md
      - Create GitHub Account: 01-set-up-machine/01-create-github-account.md
      - View Hidden Files and Extensions: 01-set-up-machine/02-view-hidden-files-and-extensions.md
      - Linux Install Tools: 01-set-up-machine/03a-linux-install-tools.md
      - Mac Install Tools: 01-set-up-machine/03b-mac-install-tools.md
      - Windows Install Tools: 01-set-up-machine/03c-windows-install-tools.md
      - Configure Git: 01-set-up-machine/04-configure-git.md
      - Create Repos Folder: 01-set-up-machine/05-create-repos-folder.md
      - Verify Setup: 01-set-up-machine/06-verify.md

  - "2: Set Up Project":
      - Overview (click here): 02-set-up-project/index.md
      - Start in GitHub: 02-set-up-project/01-start-in-github.md
      - Enable GitHub Pages: 02-set-up-project/02-enable-github-pages.md
      - Clone Repo to Local: 02-set-up-project/03-clone-repo-to-local.md
      - Install VS Code Extensions: 02-set-up-project/04-install-vscode-extensions.md
      - Set Up Virtual Environment: 02-set-up-project/05-set-up-virtual-environment.md
      - Git Add Commit Push: 02-set-up-project/06-git-add-commit-push.md
      - Update Project Files: 02-set-up-project/07-update-project-files.md

  - "3: Daily Workflow":
      - Overview (click here): 03-daily-workflow/index.md
      - Git Pull Before Changes: 03-daily-workflow/01-git-pull-before-changes.md
      - Update and Check: 03-daily-workflow/02-update-and-check.md
      - Build and Serve Docs: 03-daily-workflow/03-build-serve-docs.md
      - Run Python Script: 03-daily-workflow/04a-run-python.md
      - Run Jupyter Notebook: 03-daily-workflow/04b-run-notebook.md
      - Git Add Commit Push: 03-daily-workflow/05-git-add-commit-push.md
      - Modify and Debug: 03-daily-workflow/06-modify-and-debug.md

  - Concepts:
      - Problem Types: problem-types.md
      - Python Standard Library: py-standard-library.md
      - Python Packages (Core): py-packages-core.md
      - Python Packages (Extended): py-packages.md

  - Help:
      - Taking Screenshots: 04-help/01-taking-screenshots.md

  - Roadmap:
      - Languages: 05-roadmap/ROADMAP_LANGUAGES.md
      - Techniques: 05-roadmap/ROADMAP_TECHNIQUES.md
      - Tools: 05-roadmap/ROADMAP_TOOLS.md

  - Reference:
      - API: api.md
